### ISSUE TITLE
total number of episodes and size

### ISSUE THREAD

**Issue by xchen101** [bipster/harmontown-video-downloader#1]
Thanks @bipster for making this sweet bot. 
I had to halt and restart the download a couple of times due to connection issues, but I think I've done downloading all available video episodes -- that's 227 for me, not sure if I've missed something -- totaling 230.1G on my hard drive. 
Would be nice if there's a definite number from other users, so I know if I've got everything :)
Cheers.

**Comment by bipster** [comment]
Thanks, @xchen101 !

I updated the README with my own result: 097a10ed2f1b154ce324e7e9f170b161f0a0996e

I had the same number of videos, though slightly higher disk space usage.

That disk space difference might be benign, but you might glance over your files to see if any seem particularly small.  If the script fails to download mid-download, the file will remain in the directory but, of course, not be complete.  Depending on how you restarted things after losing the connection, I wonder if you might have a couple partial-files lingering.

Here is a list of my video files under 700 megabytes (can execute this inside your output directory to compare):
```
$ ls -l | awk '{if ($5 < 734003200) print $9}'

2014-chicago.mp4
video-episode-127.mp4
video-episode-128.mp4
video-episode-168-live-from-the-seeso-launch-at-the-new-york-television-festival-2015.mp4
video-episode-214-live-at-jfl-toronto-2016.mp4
video-episode-219-night-1-at-the-2016-new-york-city-comedy-festival.mp4
video-episode-220-night-2-at-the-2016-new-york-city-comedy-festival.mp4
video-episode-222-anne-frank-kicked-a-cat-once.mp4
video-episode-224-harmontownunder-brisbane-australia.mp4
video-episode-225-harmontownunder-melbourne-australia.mp4
video-episode-225-harmontownunder-sydney-australia-day-1.mp4
video-episode-227-harmontownunder-sydney-australia-day-2.mp4
video-episode-230-live-from-san-francisco-2017.mp4
video-episode-236-live-from-esthers-follies-at-sxsw17-in-austin-tx.mp4
video-episode-242-the-final-meltdown.mp4
video-episode-249-live-from-id10t-fest-2017.mp4
```
